spring:

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.136.114.126:3306/user_center
    username: 
    password: 
  # session 失效时间
  session:
    timeout: 86400


